/**
 * @file model_weights.h
 * @brief Placeholder for trained model weights.
 *
 * This file should be generated by the Python script (Training Page -> Export for ESP32).
 */

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <stdint.h>

/* Metadata */
#define MODEL_NUM_CLASSES 5
#define MODEL_NUM_FEATURES 16

/* Class Names */
static const char* MODEL_CLASS_NAMES[MODEL_NUM_CLASSES] = {
    "REST",
    "OPEN",
    "FIST",
    "HOOK_EM",
    "THUMBS_UP",
};

/* Feature Extractor Parameters */
#define FEAT_ZC_THRESH 0.1f
#define FEAT_SSC_THRESH 0.1f

/* LDA Intercepts/Biases */
static const float LDA_INTERCEPTS[MODEL_NUM_CLASSES] = {
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f
};

/* LDA Coefficients (Weights) */
static const float LDA_WEIGHTS[MODEL_NUM_CLASSES][MODEL_NUM_FEATURES] = {
    {0.0f},
    {0.0f},
    {0.0f},
    {0.0f},
    {0.0f}
};

#endif /* MODEL_WEIGHTS_H */
